trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectKey: 'regmut: Regex Parser'
  peojectName: 'Regex Mutaties in Stryker Mutator'

steps:
- task: DotNetCoreCLI@2
  displayName: Dotnet Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: SonarQubePrepare@4
  displayName: Prepare SonarQube
  inputs:
    SonarQube: 'SonarQube Service Connection'
    scannerMode: 'MSBuild'
    projectKey: $(projectKey)
    projectName: $(projectName)

- task: DotNetCoreCLI@2
  displayName: 'DotNet Build'
  inputs:
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Test'
  inputs:
    command: test
    projects: '**/*.UnitTest'
    arguments: '--configuration $(BuildConfiguration) --collect:"Code Coverage"'

- task: SonarQubeAnalyze@4
  displayName: Analyze with SonarQube

- task: SonarQubePublish@4
